[package]
name = "map_type"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "map_type"
crate-type = ["lib", "cdylib"]

[dependencies]
uniffi = { workspace = true, features = [
  "build",
] }

[build-dependencies]
uniffi-dart = { path = "../../", features = ["build"] }

[dev-dependencies]
uniffi-dart = { path = "../../", features = ["bindgen-tests"] }
uniffi = { workspace = true, features = [
  "bindgen-tests",
] }
anyhow = "1"
